import AppSidebar from "@/components/Layout/AppSidebar"
import NextAuthProvider from "@/components/NextAuthProvider"
import type { Metadata } from "next"
import { getServerSession } from "next-auth"
import { Inter, Lato, Roboto } from "next/font/google"
import { headers } from "next/headers"
import Image from "next/image"
import { redirect } from "next/navigation"
import { authOptions } from "../api/auth/[...nextauth]/route"
import "../globals.css"

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function AppLayout({
  children,
  ...rest
}: {
  children: React.ReactNode
}) {
  const url = headers().get("next-url")

  const session = await getServerSession(authOptions)
  if (!session) {
    redirect("/")
  }

  return (
    <html lang="en">
      <body className={roboto.className}>
        <NextAuthProvider>
          <main className="flex min-h-screen">
            <aside className="bg-blue-100 w-48 p-4 shadow">
              {session.user && session.user.image && (
                <div className="rounded-full overflow-hidden aspect-square w-24 mx-auto">
                  <Image
                    src={session?.user?.image ?? ""}
                    alt="avatar"
                    width={256}
                    height={256}
                  />
                </div>
              )}
              <AppSidebar />
            </aside>
            <div className="grow">
              <div className="bg-white m-4 p-4 shadow">{children}</div>
            </div>
          </main>
        </NextAuthProvider>
      </body>
    </html>
  )
}
