import type { Metadata } from "next"
import { Inter, Roboto } from "next/font/google"
import "../globals.css"
import Header from "@/components/Header"
import { SessionProvider } from "next-auth/react"
import NextAuthProvider from "@/components/NextAuthProvider"

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function WebsiteLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <NextAuthProvider>
          <main>
            <Header />
            <div className="p-6 max-w-4xl mx-auto">{children}</div>
          </main>
        </NextAuthProvider>
      </body>
    </html>
  )
}
